import type { AppCopy, Lang } from '@/lib/types';

/** Textes repris de l'ancienne page `apps/orbis.html`. */
const fr: AppCopy = {
  tagline: 'Arcade · réflexes · iOS',

  headline: {
    lead: 'Un toucher.',
    highlight: 'Un univers.',
  },

  intro:
    'Appuie et maintiens pour déployer un cercle de lumière. Relâche pour l’ancrer. Couvre 75 % de l’arène — sans frôler le vide.',

  stats: [
    { value: '75 %', label: 'de l’arène à couvrir' },
    { value: '1', label: 'geste' },
    { value: '∞', label: 'niveaux' },
    { value: '0', label: 'fichier audio' },
  ],

  sections: [
    {
      id: 'how-it-plays',
      kicker: 'Conçu pour l’essentiel',
      title: 'Tout tient dans un doigt posé',
      items: [
        {
          title: 'Un geste unique',
          body: 'Appuie et maintiens pour grandir. Relâche pour t’ancrer. Aucun tutoriel nécessaire — le jeu s’explique par lui-même en une seconde.',
        },
        {
          title: 'Niveaux infinis',
          body: 'Chaque niveau ajoute une couche de défi : plus de vides, formations rocheuses, courants d’eau. La difficulté grandit avec toi.',
        },
        {
          title: 'Son entièrement synthétisé',
          body: 'Aucun fichier audio. Chaque son — le grondement d’une bulle, le plop de l’ancrage, le murmure d’un courant — est généré à la main, en temps réel.',
        },
        {
          title: 'Game Center',
          body: 'Classements séparés iPhone et iPad, pour un score global et un score par niveau.',
        },
        {
          title: 'Design zen',
          body: 'Fond sombre, cercles flottants, palette épurée. Orbis a été pensé comme un objet de calme — pas comme un jeu qui te crie dessus.',
        },
        {
          title: 'Une main suffit',
          body: 'Conçu pour le pouce. Un seul point de contact, une expérience complète.',
        },
      ],
    },
    {
      id: 'gallery-tilt',
      title: 'Le jeu en images',
    },
    {
      id: 'privacy',
      kicker: 'Vie privée',
      title: 'Sans compte',
      body: 'Ta progression reste sur l’appareil ; seuls les classements passent par Game Center. Le détail des SDK intégrés figure dans la politique de confidentialité.',
    },
  ],

  cta: {
    title: 'Un doigt, une arène',
    body: 'Orbis est disponible sur l’App Store.',
  },

  meta: {
    title: 'Orbis — un toucher, un univers',
    description:
      'Appuie et maintiens pour déployer un cercle de lumière, relâche pour l’ancrer, couvre 75 % de l’arène sans frôler le vide. Niveaux infinis, son entièrement synthétisé.',
  },

  chips: [],
};

const en: AppCopy = {
  tagline: 'Arcade · reflexes · iOS',

  headline: {
    lead: 'One touch.',
    highlight: 'One universe.',
  },

  intro:
    'Press and hold to grow a circle of light. Release to anchor it. Cover 75% of the arena — without ever touching the void.',

  stats: [
    { value: '75%', label: 'of the arena to cover' },
    { value: '1', label: 'gesture' },
    { value: '∞', label: 'levels' },
    { value: '0', label: 'audio files' },
  ],

  sections: [
    {
      id: 'how-it-plays',
      kicker: 'Built around the essential',
      title: 'It all fits in one resting finger',
      items: [
        {
          title: 'A single gesture',
          body: 'Press and hold to grow. Release to anchor. No tutorial needed — the game explains itself in a second.',
        },
        {
          title: 'Endless levels',
          body: 'Each level adds a layer of challenge: more voids, rock formations, water currents. Difficulty grows with you.',
        },
        {
          title: 'Fully synthesised sound',
          body: 'No audio files at all. Every sound — the rumble of a bubble, the plop of anchoring, the murmur of a current — is generated by hand, in real time.',
        },
        {
          title: 'Game Center',
          body: 'Separate iPhone and iPad leaderboards, for an overall score and a per-level score.',
        },
        {
          title: 'Zen design',
          body: 'Dark background, floating circles, a stripped-back palette. Orbis was built as an object of calm — not a game that shouts at you.',
        },
        {
          title: 'One hand is enough',
          body: 'Designed for the thumb. A single point of contact, a complete experience.',
        },
      ],
    },
    {
      id: 'gallery-tilt',
      title: 'The game in pictures',
    },
    {
      id: 'privacy',
      kicker: 'Privacy',
      title: 'No account',
      body: 'Your progress stays on the device; only leaderboards go through Game Center. The full list of included SDKs is in the privacy policy.',
    },
  ],

  cta: {
    title: 'One finger, one arena',
    body: 'Orbis is available on the App Store.',
  },

  meta: {
    title: 'Orbis — one touch, one universe',
    description:
      'Press and hold to grow a circle of light, release to anchor it, cover 75% of the arena without touching the void. Endless levels, fully synthesised sound.',
  },

  chips: [],
};

export const pageCopy: Partial<Record<Lang, AppCopy>> = { fr, en };
