/* Dictionnaire du site — de. */
import type { SiteDict } from './keys';

export const dict: SiteDict = {
  "privacy.title": "Datenschutzerklärung",
  "privacy.updated": "Zuletzt aktualisiert: ",
  "privacy.toc": "Inhalt",
  "privacy.back": "Zurück zur Seite von {app}",
  "nav.home": "Startseite",
  "nav.privacy": "Datenschutz",
  "nav.apps": "Apps",
  "nav.games": "Spiele",
  "nav.about": "Über uns",
  "nav.follow": "Folgen",
  "hero.tagline": "Gestalter mobiler Erlebnisse.",
  "hero.sub": "Sorgfältig durchdachte Apps und Spiele für iPhone und Android — nützlich, schnell und respektvoll gegenüber Ihrer Privatsphäre.",
  "meta.home_title": "AppCraft31 — mobile Apps und Spiele aus Toulouse",
  "meta.home_description": "Unabhängiges Studio in Toulouse, Frankreich. Sorgfältig gemachte Apps und Spiele für iPhone und Android — offen darüber, was mit Ihren Daten geschieht.",
  "meta.privacy_title": "Datenschutzerklärung — {app}",
  "meta.privacy_description": "Was {app} mit Ihren Daten macht — und was nicht: lokale Speicherung, Werbung, In-App-Käufe, Nutzungsmessung und Ihre Rechte.",
  "hero.title_lead": "Ein Studio.",
  "hero.title_accent": "{count} digitale Objekte.",
  "about.stat_langs_label": "Sprachen",
  "hero.cta_apps": "Unsere Apps",
  "hero.cta_games": "Unsere Spiele",
  "featured.kicker": "Unabhängiges Studio · Toulouse",
  "featured.title": "Unsere meistgeladenen Apps",
  "featured.note": "Rangfolge nach App-Store-Downloads der letzten 28 Tage.",
  "featured.rank": "Nr. {n} im Studio",
  "featured.discover": "Entdecken",
  "featured.all": "Alle {count} Werke ansehen",
  "featured.prev": "Vorherige App",
  "featured.next": "Nächste App",
  "featured.goto": "Zu {app}",
  "featured.pause": "Automatisches Blättern anhalten",
  "featured.play": "Automatisches Blättern fortsetzen",
  "featured.label": "Ausgewählte Apps",
  "badge.available": "Verfügbar",
  "badge.soon": "Bald",
  "common.learn_more": "Mehr erfahren",
  "apps.pill": "Apps",
  "apps.title": "Werkzeuge für den Alltag",
  "apps.subtitle": "Nützlich, schnell, ohne Schnickschnack.",
  "portfolio.title": "Unsere Kreationen",
  "portfolio.subtitle": "Nützliche Apps und sorgfältig gestaltete Spiele, die Ihre Privatsphäre respektieren.",
  "portfolio.filter_all": "Alle",
  "portfolio.filter_apps": "Apps",
  "portfolio.filter_games": "Spiele",
  "games.pill": "Spiele",
  "games.title": "Spiele zum Abschalten",
  "games.subtitle": "Minimalistisch, entspannend, gemacht für die Dauer.",
  "about.title": "Über AppCraft31",
  "about.p1": "AppCraft31 ist ein unabhängiges Studio mit Sitz in Toulouse (Haute-Garonne). Ich entwerfe und entwickle mobile Apps im Alleingang — von der Idee bis zur Veröffentlichung im App Store und bei Google Play.",
  "about.p2": "Meine Philosophie: Apps, die <strong>nützlich</strong>, <strong>schnell</strong> und <strong>respektvoll</strong> sind. Keine Dark Patterns, keine übertriebene Monetarisierung, kein Weiterverkauf von Daten.",
  "about.stat_app_label": "Apps",
  "about.stat_games_label": "Spiele",
  "footer.privacy": "Datenschutz",
  "footer.support": "Support",
  "ui.theme_label": "Design wechseln",
  "ui.lang_label": "Sprache wechseln",
};
