/* Dictionnaire du site — de. */
import type { SiteDict } from './keys';

export const dict: SiteDict = {
  "nav.apps": "Apps",
  "nav.games": "Spiele",
  "nav.about": "Über uns",
  "nav.follow": "Folgen",
  "hero.tagline": "Gestalter mobiler Erlebnisse.",
  "hero.sub": "Sorgfältig durchdachte iOS-Apps und -Spiele — nützlich, schnell und respektvoll gegenüber Ihrer Privatsphäre.",
  "hero.cta_apps": "Unsere Apps",
  "hero.cta_games": "Unsere Spiele",
  "badge.available": "Verfügbar",
  "badge.soon": "Bald",
  "common.learn_more": "Mehr erfahren",
  "apps.pill": "Apps",
  "apps.title": "Werkzeuge für den Alltag",
  "apps.subtitle": "Nützlich, schnell, ohne Werbung und Tracking.",
  "portfolio.title": "Unsere Kreationen",
  "portfolio.subtitle": "Nützliche Apps und sorgfältig gestaltete Spiele, die Ihre Privatsphäre respektieren.",
  "portfolio.filter_all": "Alle",
  "portfolio.filter_apps": "Apps",
  "portfolio.filter_games": "Spiele",
  "games.pill": "Spiele",
  "games.title": "Spiele zum Abschalten",
  "games.subtitle": "Minimalistisch, entspannend, gemacht für die Dauer.",
  "about.title": "Über AppCraft31",
  "about.p1": "AppCraft31 ist ein unabhängiges Studio mit Sitz in Toulouse (Haute-Garonne). Ich entwerfe und entwickle iOS-Apps im Alleingang — von der Idee bis zur Veröffentlichung im App Store.",
  "about.p2": "Meine Philosophie: Apps, die <strong>nützlich</strong>, <strong>schnell</strong> und <strong>respektvoll</strong> sind. Keine Dark Patterns, keine übertriebene Monetarisierung, kein Weiterverkauf von Daten.",
  "about.stat_app_label": "Apps",
  "about.stat_games_label": "Spiele",
  "footer.privacy": "Datenschutz",
  "footer.support": "Support",
  "ui.theme_label": "Design wechseln",
  "ui.lang_label": "Sprache wechseln",
};
