/* Dictionnaire du site — en. */
import type { SiteDict } from './keys';

export const dict: SiteDict = {
  "privacy.title": "Privacy policy",
  "privacy.updated": "Last updated: ",
  "privacy.toc": "Contents",
  "privacy.back": "Back to the {app} page",
  "nav.home": "Home",
  "nav.privacy": "Privacy",
  "nav.apps": "Apps",
  "nav.games": "Games",
  "nav.about": "About",
  "nav.follow": "Follow us",
  "hero.tagline": "Creator of mobile experiences.",
  "hero.sub": "Thoughtfully crafted apps and games for iPhone and Android — useful, fast, and respectful of your privacy.",
  "meta.home_title": "AppCraft31 — mobile apps and games made in Toulouse",
  "meta.home_description": "Independent studio in Toulouse, France. Carefully made apps and games for iPhone and Android, upfront about what they do with your data.",
  "meta.privacy_title": "Privacy policy — {app}",
  "meta.privacy_description": "What {app} does — and does not do — with your data: local storage, advertising, in-app purchases, analytics and your rights.",
  "hero.title_lead": "One studio.",
  "hero.title_accent": "{count} digital objects.",
  "about.stat_langs_label": "Languages",
  "hero.cta_apps": "Our apps",
  "hero.cta_games": "Our games",
  "featured.kicker": "Independent studio · Toulouse",
  "featured.title": "Our most downloaded apps",
  "featured.note": "Ranked by App Store downloads over the last 28 days.",
  "featured.rank": "No. {n} in the studio",
  "featured.discover": "Discover",
  "featured.all": "See all {count} creations",
  "featured.prev": "Previous app",
  "featured.next": "Next app",
  "featured.goto": "Go to {app}",
  "featured.pause": "Pause autoplay",
  "featured.play": "Resume autoplay",
  "featured.label": "Featured apps",
  "badge.available": "Available",
  "badge.soon": "Coming soon",
  "common.learn_more": "Learn more",
  "apps.pill": "Apps",
  "apps.title": "Everyday tools",
  "apps.subtitle": "Useful, fast, no clutter.",
  "portfolio.title": "Our Creations",
  "portfolio.subtitle": "Useful apps and carefully crafted games, respectful of your privacy.",
  "portfolio.filter_all": "All",
  "portfolio.filter_apps": "Apps",
  "portfolio.filter_games": "Games",
  "games.pill": "Games",
  "games.title": "Games to get away",
  "games.subtitle": "Minimalist, zen, built to last.",
  "about.title": "About AppCraft31",
  "about.p1": "AppCraft31 is an independent studio based in Toulouse (Haute-Garonne). I design and build mobile apps solo — from the idea to the App Store and Google Play launch.",
  "about.p2": "My philosophy: apps that are <strong>useful</strong>, <strong>fast</strong>, and <strong>respectful</strong>. No dark patterns, no excessive monetization, no data sold off.",
  "about.stat_app_label": "Apps",
  "about.stat_games_label": "Games",
  "footer.privacy": "Privacy",
  "footer.support": "Support",
  "ui.theme_label": "Switch theme",
  "ui.lang_label": "Switch language",
};
