/* Dictionnaire du site — en. */
import type { SiteDict } from './keys';

export const dict: SiteDict = {
  "nav.apps": "Apps",
  "nav.games": "Games",
  "nav.about": "About",
  "nav.follow": "Follow us",
  "hero.tagline": "Creator of mobile experiences.",
  "hero.sub": "Thoughtfully crafted iOS apps and games — useful, fast, and respectful of your privacy.",
  "hero.cta_apps": "Our apps",
  "hero.cta_games": "Our games",
  "badge.available": "Available",
  "badge.soon": "Coming soon",
  "common.learn_more": "Learn more",
  "apps.pill": "Apps",
  "apps.title": "Everyday tools",
  "apps.subtitle": "Useful, fast, no ads or tracking.",
  "portfolio.title": "Our Creations",
  "portfolio.subtitle": "Useful apps and carefully crafted games, respectful of your privacy.",
  "portfolio.filter_all": "All",
  "portfolio.filter_apps": "Apps",
  "portfolio.filter_games": "Games",
  "games.pill": "Games",
  "games.title": "Games to get away",
  "games.subtitle": "Minimalist, zen, built to last.",
  "about.title": "About AppCraft31",
  "about.p1": "AppCraft31 is an independent studio based in Toulouse (Haute-Garonne). I design and build iOS apps solo — from the idea to the App Store launch.",
  "about.p2": "My philosophy: apps that are <strong>useful</strong>, <strong>fast</strong>, and <strong>respectful</strong>. No dark patterns, no excessive monetization, no data sold off.",
  "about.stat_app_label": "Apps",
  "about.stat_games_label": "Games",
  "footer.privacy": "Privacy",
  "footer.support": "Support",
  "ui.theme_label": "Switch theme",
  "ui.lang_label": "Switch language",
};
