/* Dictionnaire du site — es. */
import type { SiteDict } from './keys';

export const dict: SiteDict = {
  "nav.apps": "Aplicaciones",
  "nav.games": "Juegos",
  "nav.about": "Acerca de",
  "nav.follow": "Síguenos",
  "hero.tagline": "Creador de experiencias móviles.",
  "hero.sub": "Aplicaciones y juegos iOS pensados con cuidado: útiles, rápidos y respetuosos con tu privacidad.",
  "hero.cta_apps": "Nuestras aplicaciones",
  "hero.cta_games": "Nuestros juegos",
  "badge.available": "Disponible",
  "badge.soon": "Próximamente",
  "common.learn_more": "Saber más",
  "apps.pill": "Aplicaciones",
  "apps.title": "Herramientas para el día a día",
  "apps.subtitle": "Útiles, rápidas, sin anuncios ni rastreo.",
  "portfolio.title": "Nuestras Creaciones",
  "portfolio.subtitle": "Aplicaciones útiles y juegos cuidados, respetuosos con su privacidad.",
  "portfolio.filter_all": "Todos",
  "portfolio.filter_apps": "Aplicaciones",
  "portfolio.filter_games": "Juegos",
  "games.pill": "Juegos",
  "games.title": "Juegos para evadirte",
  "games.subtitle": "Minimalistas, zen, diseñados para durar.",
  "about.title": "Acerca de AppCraft31",
  "about.p1": "AppCraft31 es un estudio independiente con sede en Toulouse (Haute-Garonne). Diseño y desarrollo aplicaciones iOS en solitario, desde la idea hasta la publicación en la App Store.",
  "about.p2": "Mi filosofía: apps <strong>útiles</strong>, <strong>rápidas</strong> y <strong>respetuosas</strong>. Sin dark patterns, sin monetización excesiva, sin datos revendidos.",
  "about.stat_app_label": "Aplicaciones",
  "about.stat_games_label": "Juegos",
  "footer.privacy": "Privacidad",
  "footer.support": "Soporte",
  "ui.theme_label": "Cambiar de tema",
  "ui.lang_label": "Cambiar de idioma",
};
