/* Dictionnaire du site — es. */
import type { SiteDict } from './keys';

export const dict: SiteDict = {
  "privacy.title": "Política de privacidad",
  "privacy.updated": "Última actualización: ",
  "privacy.toc": "Índice",
  "privacy.back": "Volver a la página de {app}",
  "nav.home": "Inicio",
  "nav.privacy": "Privacidad",
  "nav.apps": "Aplicaciones",
  "nav.games": "Juegos",
  "nav.about": "Acerca de",
  "nav.follow": "Síguenos",
  "hero.tagline": "Creador de experiencias móviles.",
  "hero.sub": "Aplicaciones y juegos para iPhone y Android pensados con cuidado: útiles, rápidos y respetuosos con tu privacidad.",
  "meta.home_title": "AppCraft31 — aplicaciones y juegos móviles hechos en Toulouse",
  "meta.home_description": "Estudio independiente de Toulouse (Francia). Aplicaciones y juegos cuidados para iPhone y Android, claros sobre lo que hacen con tus datos.",
  "meta.privacy_title": "Política de privacidad — {app}",
  "meta.privacy_description": "Lo que {app} hace —y lo que no hace— con tus datos: almacenamiento local, publicidad, compras integradas, analítica y tus derechos.",
  "hero.title_lead": "Un estudio.",
  "hero.title_accent": "{count} objetos digitales.",
  "about.stat_langs_label": "Idiomas",
  "hero.cta_apps": "Nuestras aplicaciones",
  "hero.cta_games": "Nuestros juegos",
  "badge.available": "Disponible",
  "badge.soon": "Próximamente",
  "common.learn_more": "Saber más",
  "apps.pill": "Aplicaciones",
  "apps.title": "Herramientas para el día a día",
  "apps.subtitle": "Útiles, rápidas, sin complicaciones.",
  "portfolio.title": "Nuestras Creaciones",
  "portfolio.subtitle": "Aplicaciones útiles y juegos cuidados, respetuosos con su privacidad.",
  "portfolio.filter_all": "Todos",
  "portfolio.filter_apps": "Aplicaciones",
  "portfolio.filter_games": "Juegos",
  "games.pill": "Juegos",
  "games.title": "Juegos para evadirte",
  "games.subtitle": "Minimalistas, zen, diseñados para durar.",
  "about.title": "Acerca de AppCraft31",
  "about.p1": "AppCraft31 es un estudio independiente con sede en Toulouse (Haute-Garonne). Diseño y desarrollo aplicaciones móviles en solitario, desde la idea hasta la publicación en la App Store y Google Play.",
  "about.p2": "Mi filosofía: apps <strong>útiles</strong>, <strong>rápidas</strong> y <strong>respetuosas</strong>. Sin dark patterns, sin monetización excesiva, sin datos revendidos.",
  "about.stat_app_label": "Aplicaciones",
  "about.stat_games_label": "Juegos",
  "footer.privacy": "Privacidad",
  "footer.support": "Soporte",
  "ui.theme_label": "Cambiar de tema",
  "ui.lang_label": "Cambiar de idioma",
};
