/* Dictionnaire du site — référence des clés. */

export const dict = {
  "privacy.title": "Politique de confidentialité",
  "privacy.updated": "Dernière mise à jour : ",
  "privacy.toc": "Sommaire",
  "privacy.back": "Retour à la page de {app}",
  "nav.home": "Accueil",
  "nav.privacy": "Confidentialité",
  "nav.apps": "Applications",
  "nav.games": "Jeux",
  "nav.about": "À propos",
  "nav.follow": "Nous suivre",
  "hero.tagline": "Créateur d'expériences mobiles.",
  "hero.sub": "Des applications et des jeux pour iPhone et Android, pensés avec soin — utiles, rapides et respectueux de votre vie privée.",
  "meta.home_title": "AppCraft31 — applications et jeux mobiles faits à Toulouse",
  "meta.home_description": "Studio indépendant toulousain. Des applications et des jeux soignés pour iPhone et Android, qui disent franchement ce qu’ils font de vos données.",
  "meta.privacy_title": "Politique de confidentialité — {app}",
  "meta.privacy_description": "Ce que {app} fait — et ne fait pas — de vos données : stockage local, publicité, achats intégrés, mesure d’audience et vos droits.",
  "hero.title_lead": "Un studio.",
  "hero.title_accent": "{count} objets numériques.",
  "about.stat_langs_label": "Langues",
  "hero.cta_apps": "Nos applications",
  "hero.cta_games": "Nos jeux",
  "badge.available": "Disponible",
  "badge.soon": "Bientôt",
  "common.learn_more": "En savoir plus",
  "apps.pill": "Applications",
  "apps.title": "Des outils du quotidien",
  "apps.subtitle": "Utiles, rapides, sans pub ni tracking.",
  "portfolio.title": "Nos Créations",
  "portfolio.subtitle": "Des applications utiles et des jeux soignés, respectueux de votre vie privée.",
  "portfolio.filter_all": "Tout",
  "portfolio.filter_apps": "Applications",
  "portfolio.filter_games": "Jeux",
  "games.pill": "Jeux",
  "games.title": "Des jeux pour s'évader",
  "games.subtitle": "Minimalistes, zen, conçus pour durer.",
  "about.title": "À propos d'AppCraft31",
  "about.p1": "AppCraft31 est un studio indépendant basé à Toulouse (Haute-Garonne). Je conçois et développe des applications mobiles en solo — de l'idée à la mise en ligne sur l'App Store et Google Play.",
  "about.p2": "Ma philosophie : des apps <strong>utiles</strong>, <strong>rapides</strong> et <strong>respectueuses</strong>. Pas de dark patterns, pas de monétisation à outrance, pas de données revendues.",
  "about.stat_app_label": "Applications",
  "about.stat_games_label": "Jeux",
  "footer.privacy": "Confidentialité",
  "footer.support": "Support",
  "ui.theme_label": "Changer de thème",
  "ui.lang_label": "Changer de langue",
} as const;
