/* Dictionnaire du site — référence des clés. */

export const dict = {
  "nav.apps": "Applications",
  "nav.games": "Jeux",
  "nav.about": "À propos",
  "nav.follow": "Nous suivre",
  "hero.tagline": "Créateur d'expériences mobiles.",
  "hero.sub": "Des applications et des jeux iOS pensés avec soin — utiles, rapides et respectueux de votre vie privée.",
  "hero.cta_apps": "Nos applications",
  "hero.cta_games": "Nos jeux",
  "badge.available": "Disponible",
  "badge.soon": "Bientôt",
  "common.learn_more": "En savoir plus",
  "apps.pill": "Applications",
  "apps.title": "Des outils du quotidien",
  "apps.subtitle": "Utiles, rapides, sans pub ni tracking.",
  "portfolio.title": "Nos Créations",
  "portfolio.subtitle": "Des applications utiles et des jeux soignés, respectueux de votre vie privée.",
  "portfolio.filter_all": "Tout",
  "portfolio.filter_apps": "Applications",
  "portfolio.filter_games": "Jeux",
  "games.pill": "Jeux",
  "games.title": "Des jeux pour s'évader",
  "games.subtitle": "Minimalistes, zen, conçus pour durer.",
  "about.title": "À propos d'AppCraft31",
  "about.p1": "AppCraft31 est un studio indépendant basé à Toulouse (Haute-Garonne). Je conçois et développe des applications iOS en solo — de l'idée à la mise en ligne sur l'App Store.",
  "about.p2": "Ma philosophie : des apps <strong>utiles</strong>, <strong>rapides</strong> et <strong>respectueuses</strong>. Pas de dark patterns, pas de monétisation à outrance, pas de données revendues.",
  "about.stat_app_label": "Applications",
  "about.stat_games_label": "Jeux",
  "footer.privacy": "Confidentialité",
  "footer.support": "Support",
  "ui.theme_label": "Changer de thème",
  "ui.lang_label": "Changer de langue",
} as const;
