/* Dictionnaire du site — ja. */
import type { SiteDict } from './keys';

export const dict: SiteDict = {
  "nav.apps": "アプリ",
  "nav.games": "ゲーム",
  "nav.about": "概要",
  "nav.follow": "フォローする",
  "hero.tagline": "モバイル体験を、つくる。",
  "hero.sub": "丁寧に設計したiOSアプリとゲーム。役立ち、軽快で、あなたのプライバシーを大切にします。",
  "hero.cta_apps": "アプリを見る",
  "hero.cta_games": "ゲームを見る",
  "badge.available": "配信中",
  "badge.soon": "近日公開",
  "common.learn_more": "詳しく見る",
  "apps.pill": "アプリ",
  "apps.title": "毎日に役立つツール",
  "apps.subtitle": "役立ち、軽快、広告もトラッキングもなし。",
  "portfolio.title": "プロダクト",
  "portfolio.subtitle": "プライバシーを尊重した、便利なアプリと丁寧に作られたゲーム。",
  "portfolio.filter_all": "すべて",
  "portfolio.filter_apps": "アプリ",
  "portfolio.filter_games": "ゲーム",
  "games.pill": "ゲーム",
  "games.title": "ひと息つけるゲーム",
  "games.subtitle": "ミニマルで、心地よく、長く遊べる。",
  "about.title": "AppCraft31について",
  "about.p1": "AppCraft31は、Toulouse(Haute-Garonne)を拠点とする独立系スタジオです。アイデアからApp Storeでの公開まで、iOSアプリをひとりで設計・開発しています。",
  "about.p2": "私の哲学は、<strong>役立ち</strong>、<strong>軽快</strong>で、<strong>誠実</strong>なアプリ。ダークパターンも、過剰な収益化も、データの転売もありません。",
  "about.stat_app_label": "アプリ",
  "about.stat_games_label": "ゲーム",
  "footer.privacy": "プライバシー",
  "footer.support": "サポート",
  "ui.theme_label": "テーマを切り替え",
  "ui.lang_label": "言語を切り替え",
};
