/* Dictionnaire du site — ko. */
import type { SiteDict } from './keys';

export const dict: SiteDict = {
  "privacy.title": "개인정보 처리방침",
  "privacy.updated": "최종 수정일: ",
  "privacy.toc": "목차",
  "privacy.back": "{app} 페이지로 돌아가기",
  "nav.home": "홈",
  "nav.privacy": "개인정보",
  "nav.apps": "앱",
  "nav.games": "게임",
  "nav.about": "소개",
  "nav.follow": "팔로우하기",
  "hero.tagline": "모바일 경험을 창조합니다.",
  "hero.sub": "정성껏 설계한 iPhone·Android 앱과 게임 — 유용하고, 빠르며, 당신의 프라이버시를 존중합니다.",
  "meta.home_title": "AppCraft31 — 툴루즈에서 만든 모바일 앱과 게임",
  "meta.home_description": "프랑스 툴루즈의 독립 스튜디오. iPhone과 Android를 위해 정성껏 만든 앱과 게임, 그리고 데이터 처리에 대한 솔직한 설명.",
  "meta.privacy_title": "개인정보 처리방침 — {app}",
  "meta.privacy_description": "{app}이 데이터로 하는 일과 하지 않는 일: 기기 내 저장, 광고, 인앱 구매, 이용 통계, 그리고 이용자의 권리.",
  "hero.title_lead": "하나의 스튜디오.",
  "hero.title_accent": "{count}개의 디지털 프로덕트.",
  "about.stat_langs_label": "지원 언어",
  "hero.cta_apps": "앱 둘러보기",
  "hero.cta_games": "게임 둘러보기",
  "featured.kicker": "독립 스튜디오 · 툴루즈",
  "featured.title": "가장 많이 다운로드된 앱",
  "featured.note": "최근 28일간 App Store 다운로드 수 기준 순위입니다.",
  "featured.rank": "스튜디오 {n}위",
  "featured.discover": "자세히 보기",
  "featured.all": "작품 {count}개 모두 보기",
  "featured.prev": "이전 앱",
  "featured.next": "다음 앱",
  "featured.goto": "{app}(으)로 이동",
  "featured.pause": "자동 넘김 일시정지",
  "featured.play": "자동 넘김 재개",
  "featured.label": "추천 앱",
  "badge.available": "출시됨",
  "badge.soon": "출시 예정",
  "common.learn_more": "자세히 보기",
  "apps.pill": "앱",
  "apps.title": "일상을 위한 도구",
  "apps.subtitle": "유용하고 빠르며, 군더더기가 없습니다.",
  "portfolio.title": "우리의 작품",
  "portfolio.subtitle": "개인정보를 존중하고 정성스럽게 만든 유용한 앱과 게임.",
  "portfolio.filter_all": "전체",
  "portfolio.filter_apps": "앱",
  "portfolio.filter_games": "게임",
  "games.pill": "게임",
  "games.title": "일상에서 벗어나는 게임",
  "games.subtitle": "미니멀하고 편안하며, 오래 즐기도록 만들었습니다.",
  "about.title": "AppCraft31 소개",
  "about.p1": "AppCraft31은 Toulouse(Haute-Garonne)에 자리한 독립 스튜디오입니다. 아이디어부터 App Store와 Google Play 출시까지, 모바일 앱을 혼자서 기획하고 개발합니다.",
  "about.p2": "제 철학은 <strong>유용하고</strong>, <strong>빠르며</strong>, <strong>존중하는</strong> 앱입니다. 다크 패턴도, 과도한 수익화도, 데이터 판매도 없습니다.",
  "about.stat_app_label": "앱",
  "about.stat_games_label": "게임",
  "footer.privacy": "개인정보 보호",
  "footer.support": "지원",
  "ui.theme_label": "테마 변경",
  "ui.lang_label": "언어 변경",
};
