/* Dictionnaire du site — ko. */
import type { SiteDict } from './keys';

export const dict: SiteDict = {
  "nav.apps": "앱",
  "nav.games": "게임",
  "nav.about": "소개",
  "nav.follow": "팔로우하기",
  "hero.tagline": "모바일 경험을 창조합니다.",
  "hero.sub": "정성껏 설계한 iOS 앱과 게임 — 유용하고, 빠르며, 당신의 프라이버시를 존중합니다.",
  "hero.cta_apps": "앱 둘러보기",
  "hero.cta_games": "게임 둘러보기",
  "badge.available": "출시됨",
  "badge.soon": "출시 예정",
  "common.learn_more": "자세히 보기",
  "apps.pill": "앱",
  "apps.title": "일상을 위한 도구",
  "apps.subtitle": "유용하고 빠르며, 광고와 추적이 없습니다.",
  "portfolio.title": "우리의 작품",
  "portfolio.subtitle": "개인정보를 존중하고 정성스럽게 만든 유용한 앱과 게임.",
  "portfolio.filter_all": "전체",
  "portfolio.filter_apps": "앱",
  "portfolio.filter_games": "게임",
  "games.pill": "게임",
  "games.title": "일상에서 벗어나는 게임",
  "games.subtitle": "미니멀하고 편안하며, 오래 즐기도록 만들었습니다.",
  "about.title": "AppCraft31 소개",
  "about.p1": "AppCraft31은 Toulouse(Haute-Garonne)에 자리한 독립 스튜디오입니다. 아이디어부터 App Store 출시까지, iOS 앱을 혼자서 기획하고 개발합니다.",
  "about.p2": "제 철학은 <strong>유용하고</strong>, <strong>빠르며</strong>, <strong>존중하는</strong> 앱입니다. 다크 패턴도, 과도한 수익화도, 데이터 판매도 없습니다.",
  "about.stat_app_label": "앱",
  "about.stat_games_label": "게임",
  "footer.privacy": "개인정보 보호",
  "footer.support": "지원",
  "ui.theme_label": "테마 변경",
  "ui.lang_label": "언어 변경",
};
